### ISSUE TITLE
[1.12.2] Black Screen Then Crash

### ISSUE THREAD

**Issue by TCreopargh** [Meldexun/EntityCulling#18] opened 2021-03-28 03:04 UTC
**Describe the bug**
Original Thread: https://github.com/TCreopargh/GreedyCraft/issues/157
Basically some of my modpack users just encounter a black or white screen when joining a world after my modpack updated EntityCulling to 4.0.x, crash report below.

Disabling EntityCulling seems to fix this problem.

**To Reproduce**
Exact steps to reproduce is currently unknown because other users playing the same version don't have any problem, but it might be related to chaotic stabilized mob spawners from draconic evolution.
Using magic mirror from BountifulBaubles also seems to cause this issue

**Expected behavior**
The game doesn't crash

**Screenshots**

**Versions**
Entity Culling: 4.0.5
Forge:  14.23.5.2855
Minecraft: 1.12.2
Optifine: OptiFine_1.12.2_HD_U_G5

**Other**
Crash report (upload as a file): https://paste.ubuntu.com/p/5YydGVSF66/
Latest log (upload as a file): 
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug):
Other mods (that are also installed): See crash report

**Comment by Meldexun** [comment] 2021-03-28 21:02
This exception gets thrown when a thread adds/removes an element from a list while another thread is iterating over that list.
But I'm unable to reproduce the issue.

So it would be nice if you (or the person who experienced the bug) could install this dev version and join a world and fly around for a bit.
Even though this version does not crash does not mean that the bug is fixed. It just catches the exception, prints a message in the log and continues. That also means that I will need the log file instead of a crash report.
[EntityCullingDev.zip](https://github.com/Meldexun/EntityCulling/files/6218042/EntityCullingDev.zip)

**Comment by Meldexun** [comment] 2021-04-21 18:23
Should be fixed in v4.1.2

**Closed by Meldexun** 2021-04-21 18:23 UTC
