### ISSUE TITLE
1.12.2 Quark Crash

### ISSUE THREAD

**Issue by mxnmnm** [Meldexun/EntityCulling#42] opened 2021-12-07 11:24 UTC
**Describe the bug**
Crash with quark

**To Reproduce**
1. Have quark pipes placed
2. Wait around
3. Randomly crash

**Expected behavior**
no crash

**Versions**
Entity Culling: 4.2.1
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Other**
I tried blacklisting quark pipes but it didn't fix things :(

Crash report (upload as a file): https://gist.github.com/mxnmnm/c2581cacc187a66fb39753d363fc04b5

**Comment by Meldexun** [comment] 2021-12-13 23:45
Duplicate of #41

**Closed by Meldexun** 2021-12-13 23:45 UTC
