### ISSUE TITLE
[1.12.2] Crash after joining a world

### ISSUE THREAD

**Issue by JustDesoroxxx** [Meldexun/EntityCulling#77] opened 2022-08-09 14:27 UTC
**Describe the bug**
After joining a world the game crash after a second.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Launch Minecraft
2. Join or create a world
3. Wait for it to load
4. Once loaded the game crashed

**Versions**
Entity Culling: 6.2.1
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

**Hardware**
CPU: Ryzen 7 5800X
RAM: 32 GB 2666 Mhz (Any amount allocated to MC will cause a crash)
GPU: Asus Radeon RX 6500 XT
VRAM: 4 GB

**Log File**
[Log]
[Log with RenderLib debug]
Debug Log (Is a file because it's too long): [debug.log]\(https://github.com/Meldexun/EntityCulling/files/9291526/debug.log)
Debug Log with RenderLib debug (Still a file): [debug.log](https://github.com/Meldexun/EntityCulling/files/9291876/debug.log)
[Crash Report]
[Crash Report with RenderLib debug]
[Crash Report Without Optifine]

[Log]: https://mclo.gs/TXVizSU
[Log with RenderLib debug]: https://mclo.gs/lcwX9dX
[Crash Report]: https://mclo.gs/hDXPCM7
[Crash Report with RenderLib debug]: https://mclo.gs/VKbIAzL
[Crash Report Without Optifine]: https://mclo.gs/aIdHD3v

**Comment by JustDesoroxxx** [comment] 2022-08-09 14:41
After testing this issue only occurs in 6.2.1, I can play normally in 6.1.0

**Comment by JustDesoroxxx** [comment] 2022-08-09 14:53
Added Log, Debug Log and crash report with RenderLib debug enabled

**Comment by Meldexun** [comment] 2022-08-09 16:30
Please follow the issue template completely next time.

**Comment by Meldexun** [comment] 2022-08-09 16:30
Duplicate of #74

**Closed by Meldexun** 2022-08-09 16:30 UTC
Labels: bug
