### ISSUE TITLE
openglBasedCulling [1.12.2-5.2.0]

### ISSUE THREAD

**Issue by Aeron216** [Meldexun/EntityCulling#56] opened 2022-03-02 11:58 UTC
**Describe the bug**
No matter what, all entities get culled when openglBasedCulling is enabled, which is enabled by default.

**To Reproduce**
1. Update from 5.1.1 to 5.2.0
2. Default config file except for disabledInSpectator switched to false

CPU: R7 3700x
GPU: RX 580
OS: Windows 10

**Screenshots/Videos**

**5.2.0**
Invisible mobs

https://youtu.be/wiI5-Eff_cA

**5.1.1**
Working

https://youtu.be/1lv4BAbqlAY

**Versions**
Entity Culling: 1.12.2-5.2.0
Forge: 2860
Minecraft: 1.12.2
Other mods: https://gist.github.com/Aeron216/8e93a8286f30a41a10f966a2e11ccb73
**Log File**
Debug file is over 80MB so gist wont let me upload it. Let me know if you really need it and a site for me to upload it.

**Comment by Meldexun** [comment] 2022-03-02 13:58
I am unable to reproduce this.
Can you try deleting the mod file and the config file and redownloading the mod afterwards?
Or it might be caused by another mod you have installed.
If that all doesn't work there might be some information in the log file.

**Comment by Meldexun** [comment] 2022-03-04 15:54
Then it's maybe caused by another mod.

**Comment by xJon** [comment] 2022-03-05 19:29
I also cannot reproduce this issue when in combination of [Hexxit II](https://www.technicpack.net/modpack/hexxit-ii.896745/mods) or [The 1.12.2 Pack](https://www.technicpack.net/modpack/the-1122-pack.1406454/mods)'s mod collections.
I'm using an RTX 2060 SUPER graphics card, perhaps this is an AMD issue?

**Comment by TheSnowyChickens** [comment] 2022-03-10 19:56
1.12.2 custom pack, 3070 TI GPU
![grafik](https://user-images.githubusercontent.com/29357962/157744200-d23e32d0-37cf-4202-92dc-7908ac71e406.png)

no problems with 5.2.0
(I blacklisted travel anchors)

**Comment by xJon** [comment] 2022-03-12 16:38
@Aeron216 Can you reproduce this issue on your system without the other mods installed?

**Comment by Pyker** [comment] 2022-03-12 17:14
I can also confirm that this happens on a clean Forge 1.12.2 install with just this mod (disabling openGlBasedCulling fixes it).

**Comment by Aeron216** [comment] 2022-03-12 18:24
Sure thing:

https://gfycat.com/shadowyseveralasiaticlesserfreshwaterclam

**Comment by Tskuno** [comment] 2022-03-12 18:50
I have ran into this issue as well, is an AMD laptop. So might be an odd error with AMD?

**Comment by Tskuno** [comment] 2022-03-12 20:44
Using my desktop (GTX 1070TI) Ryzen 2700X I have the issue but it's minor, things aren't visable right away, such as if I use the wearable backpack mod,  and place the backpack down I cannot see it for a moment. It also does this with chests when I place them. I hope this helps to actually pin down the bug some

**Comment by democat3457** [comment] 2022-03-12 21:41
Can confirm it's an issue with AMD GPUs - running Rebirth of the Night v3.0.0 (as reported by over a dozen people)

**Comment by Meldexun** [comment] 2022-03-13 19:54
[EntityCullingTestVersion.zip](https://github.com/Meldexun/EntityCulling/files/8240320/EntityCullingTestVersion.zip)
Can anyone who has experienced this issue test if this test build fixes the issue? (You have to unpack the file)

**Comment by Pyker** [comment] 2022-03-13 20:13
I confirm that the test build fixes the issue for me.

**Comment by democat3457** [comment] 2022-03-14 06:20
can confirm that at least one other person with this issue had it fixed with this jar as well

**Comment by Aeron216** [comment] 2022-03-16 11:13
This particular issue does seem to go away with the jar in the comments.

However, can anyone with an AMD card confirm if they also have this other issue presented in this video?

Ever since updating past 4.1.5 Ive felt that the mod wasnt culling anything at all, never felt as smooth as before. Not sure if this is a good test but just go into spectator mod and underground like in the video and with disabledInSpectator on false:

https://youtu.be/h2i0667D12E

Once you disable openglBasedCulling entities start getting hidden once again. Maybe AMD is just bad at this.

**Comment by Meldexun** [comment] 2022-03-16 14:29
Your test is faulty. The new culling mode works by rendering the entities bounding box without filling the color or depth buffer and instead the entity is marked visible when at least 1 fragment passes the depth test. That means whenever you could see 1 (or more) pixel of the bounding box if it would be rendered then the entity will be rendered.
So it doesn't matter if there are blocks between the camera and the entity the only thing that matters is if the entity bounding box is fully visually obscured.

**Comment by Meldexun** [comment] 2022-03-18 02:06
Fixed in v1.12.2-5.2.1

**Closed by Meldexun** 2022-03-18 02:06 UTC
Labels: bug
