### ISSUE TITLE
Extra Utilities Crash

### ISSUE THREAD

**Issue by mxnmnm** [Meldexun/EntityCulling#44] opened 2021-12-10 09:02 UTC
**Describe the bug**
Random crash booting up the game

**To Reproduce**
1. I was just booting up my game and it crashy :( (no clue why other than it having something to do with extra utilities)

**Expected behavior**
No crashy

**Versions**
Entity Culling: 4.2.1
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Other**
Crash report: https://gist.github.com/mxnmnm/33d44c3796f469a973a31313622b60a7

**Comment by Meldexun** [comment] 2021-12-13 23:46
Duplicate of #41

**Closed by Meldexun** 2021-12-13 23:46 UTC

**Comment by mxnmnm** [comment] 2021-12-15 08:16
It still happens on latest version https://gist.github.com/mxnmnm/dc2292677b27fdad874fde4af99929c5

**Comment by Meldexun** [comment] 2021-12-15 14:28
Don't comment on issues that are marked as duplicates and instead comment on the original issue.
(Nontheless EntityCulling v1.12.2-4.2.4 should fix this issue)
