### ISSUE TITLE
[1.12.2] NullPointerException when accessing visibility buffer

### ISSUE THREAD

**Issue by Sereath** [Meldexun/EntityCulling#76] opened 2022-08-06 21:22 UTC
**Describe the bug**
Client crashing within minutes of joining the world.

**To Reproduce**
1. Update from 6.1.0 to 6.2.1

**Screenshots/Videos**

The game changes to the main menu background when crashing. It doesn't even notify me about the crash, it simply freezes.
![crashscreen](https://user-images.githubusercontent.com/54506307/183264828-9682bbd3-46c4-4e5b-9f62-a12d5a2c5334.png)

**Versions**
Entity Culling: 6.2.1
Forge: 2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
https://www.curseforge.com/minecraft/modpacks/srp-qz/files/3921007

**Log File**
https://mclo.gs/bYOJNOH

Crash logs:

1st
https://mclo.gs/XgEVwRn

2nd
https://mclo.gs/j9f7h30

However, after those first 2 it's now blaming Xaero: 
https://mclo.gs/jYu9epI
https://mclo.gs/nMfGuUU

Which is odd because the only mods I recently updated were Entity Culling, RenderLib and FancyMenu

After downgrading from 6.2.1 to 6.1.0
and the library, from 1.1.2 to 1.1.1
I'm no longer crashing and it has been over 30 mins.

Another thing, none of the other players (two of them) in this server have crashed with this update. Both have Nvidia cards while I have an AMD card.

Edit:
Shortly after this one of them also crashed.

Specs:
Ryzen 7 3700X
RX 580
W10

**Comment by Meldexun** [comment] 2022-08-08 19:25
Please update RenderLib to v1.12.2-1.1.3 and set the `enableGLDebug` config option from RenderLib to true. Then try to reproduce the issue and upload the log file (for example https://gist.github.com/).

**Comment by 623667595** [comment] 2022-08-09 04:42
Or black screen.
![image](https://user-images.githubusercontent.com/88877796/183565797-7e51ae7c-6187-4013-a221-8e310ab6f700.png)
[crash-2022-08-09_12.39.04-client.txt](https://github.com/Meldexun/EntityCulling/files/9286785/crash-2022-08-09_12.39.04-client.txt)

**Comment by Meldexun** [comment] 2022-08-09 16:32
> Or black screen. ![image](https://user-images.githubusercontent.com/88877796/183565797-7e51ae7c-6187-4013-a221-8e310ab6f700.png) [crash-2022-08-09_12.39.04-client.txt](https://github.com/Meldexun/EntityCulling/files/9286785/crash-2022-08-09_12.39.04-client.txt)

This is not related to this issue

**Comment by Sereath** [comment] 2022-08-09 22:44
latest.log
https://gist.github.com/Sereath/505e9cc61ae38c09922357a1e1475c31

crash
https://gist.github.com/Sereath/b7a91fbfdf5c8c9a0e130cb744f7a68a

**Comment by Meldexun** [comment] 2022-08-09 23:03
Have you enable the `enableGLDebug` option ingame? Because you have to restart the game after changing that config option.

**Comment by Sereath** [comment] 2022-08-09 23:16
I did it when it was closed

**Comment by Sereath** [comment] 2022-08-09 23:31
Did it again by using the gui ingame instead of editing the cfg file when closed:

latest.log
https://gist.github.com/Sereath/075059ec78d9963ba4ddaa16e2bea381

crash
https://gist.github.com/Sereath/18478d4ef9d262549814624016f9d332

**Comment by Sereath** [comment] 2022-08-09 23:50
I have reported the Xaeros Map crash to the dev. However, my initial crashes didnt point to Xaeros as the culprit as shown above. I havent been able to replicate those initial crashes ever since, its very weird.

**Comment by Meldexun** [comment] 2022-08-10 12:57
Should be fixed in v1.12.2-6.2.2

**Closed by Meldexun** 2022-08-10 12:57 UTC
Labels: bug, unconfirmed
