### ISSUE TITLE
[1.12.2] Crash with 6.2.1

### ISSUE THREAD

**Issue by xJon** [Meldexun/EntityCulling#75] opened 2022-08-06 20:53 UTC
**Describe the bug**
A couple of crashes with the latest version, first from chiselling grass apparently, second was one random.

**Versions**
Entity Culling: `6.2.1`
Forge: `14.23.5.2860`
Minecraft: `1.12.2`
Other mods (necessary to reproduce the bug): Chisel, and unknown

**Log File**
https://mclo.gs/K8eqJtp
https://mclo.gs/tIvVf8B
https://mclo.gs/BXusisA

**Comment by Krutoy242** [comment] 2022-08-08 09:16
Have same issue

**Comment by Gandalf360one** [comment] 2022-08-08 09:19
Do you have mixin installed ?

**Comment by Meldexun** [comment] 2022-08-08 19:26
Please update RenderLib to v1.12.2-1.1.3 and set the `enableGLDebug` config option from RenderLib to true. Then try to reproduce the issue and upload the log file (for example https://gist.github.com/).

**Comment by JLenander** [comment] 2022-08-09 00:05
I had the same issue but happening when I complete a quark birch double chest (place down two quark birch chests to make a double chest).

Renderlib: `1.1.3`
Entity Culling: `6.2.1`
Forge: `14.23.5.2859`
MC: `1.12.2`
Quark `vr1.6-179`

Heres the debug log with renderlib v1.12.2-1.1.3: https://gist.github.com/JLenander/21a327a60ea45456d266570a503cbf88

**Comment by Meldexun** [comment] 2022-08-09 16:26
> second was one random
Please create a new issue when reporting multiple issues.

**Comment by Meldexun** [comment] 2022-08-09 16:28
The third crash should be reported to the craftingtableiv mod.

**Comment by Meldexun** [comment] 2022-08-09 16:28
Duplicate of #74

**Closed by Meldexun** 2022-08-09 16:28 UTC
Labels: bug
