### ISSUE TITLE
[1.16.5] 32MB RAM doesn't seem to be enough

### ISSUE THREAD

**Issue by NillerMedDild** [Meldexun/EntityCulling#15] opened 2021-03-21 11:18 UTC
**Describe the bug**
Out of RAM crash.

**To Reproduce**
1. Add Entity Culling to a large modpack, such as Enigmatica 6
2. Join a world
3. Move around a bit for about 5 minutes (seems a bit random)
4. Crash

**Expected behavior**
No crash

**Versions**
Entity Culling: EntityCulling-1.16.5-2.0.6
Forge: 1.16.5-36.1.0
Minecraft: 1.16.5

**Other**
Crash report (upload as a file): No crash report generated, had to kill the process
Latest log (upload as a file): [latest.log](https://github.com/Meldexun/EntityCulling/files/6177274/latest.log) Last line
Singleplayer/Multiplayer: SP
Other mods (that are necessary to produce the bug): None in particular, just enough to increase RAM load I think
Other mods (that are also installed): https://github.com/NillerMedDild/Enigmatica6/blob/master/MODLIST.md

**Comment by Meldexun** [comment] 2021-03-21 11:48
Why do you tthink this is a Bug of entity culling?

**Comment by NillerMedDild** [comment] 2021-03-21 19:02
Well it started when I added Entity Culling and stopped when I removed it :P

**Comment by Meldexun** [comment] 2021-03-21 21:13
I don't see why this should be a bug in Entity Culling. It's just an OUT_OF_MEMORY error. What GPU are you using?

**Comment by NillerMedDild** [comment] 2021-03-21 21:15
NVIDIA GeForce GTX 1060

**Comment by xameryn** [comment] 2021-04-10 00:15
A similar thing happens to me when using the mod, was reproducible by quickly loading a large number of chunks ie. changing render distance from 2 to 8, going through a portal, going fast etc. It caused my game to jump from its ~4GB of allocated ram to 12GB which would then freeze and crash the game. It began upon adding the mod and no longer happened after removing it. It was fairly inconsistent though so if it pops back up I'll update this.

**Comment by Meldexun** [comment] 2021-04-10 00:21
Which version where you using?

**Comment by xameryn** [comment] 2021-04-10 00:26
Unsure the exact version because I deleted it while trying to fix it, was a 1.16 version a few versions back. Will see if a newer version fixes it.

**Comment by Meldexun** [comment] 2021-04-13 13:18
Should be fixed in v2.1.1

**Closed by Meldexun** 2021-04-13 13:18 UTC
Labels: not reproducible
