### ISSUE TITLE
IllegalAccessorError

### ISSUE THREAD

**Issue by kreezxil** [Meldexun/EntityCulling#43] opened 2021-12-09 15:49 UTC
## Server Disconnect When industrial foregoing blocks placed.

Was working to unlock more chickens. Made the first couple machines to get started into Industrial Foregoing (Tree Fluid Extractor and the Latex Processing Unit). Placed them down into the world, and the client disconnected from the server. Said that a Fatal Error occurred. Did not occur subsequent times. After breaking a replacing, I could place them with abandon. Placed down a third machine (Dye Mixer) and no issues. Tested in single player, and no issues there either. No crash report generated, only some lines in the latest log.

Reason for Crash: [https://gist.github.com/defranke00/53edfb5ff3f09efebd859816dd090f6c](https://gist.github.com/defranke00/53edfb5ff3f09efebd859816dd090f6c)

original bug report at: https://gitlab.com/kreezxil/cobbleblock/-/issues/36

**Versions**
Entity Culling: 4.2.1
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Other**
I will get these others to you as soon as the player who reported the original issue sends me the files.

**Comment by Meldexun** [comment] 2021-12-13 23:46
Duplicate of #41

**Closed by Meldexun** 2021-12-13 23:46 UTC
